name: Check Old Open Branches and Send Email

on:
  workflow_dispatch:

jobs:
  setup-java:
    name: Setup Java
    runs-on: ubuntu-latest
    steps:
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

  send-email:
    name: Send Email
    runs-on: ubuntu-latest
    needs: setup-java
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Maven Project
        run: |
          mkdir -p email-sender/src/main/java
          cat > email-sender/pom.xml << 'EOF'
          <project xmlns="http://maven.apache.org/POM/4.0.0" 
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
              <modelVersion>4.0.0</modelVersion>
              <groupId>com.example</groupId>
              <artifactId>email-sender</artifactId>
              <version>1.0-SNAPSHOT</version>

              <dependencies>
                  <dependency>
                      <groupId>com.sun.mail</groupId>
                      <artifactId>javax.mail</artifactId>
                      <version>1.6.2</version>
                  </dependency>
              </dependencies>
          </project>
          EOF
        
      - name: Create Java Email Sender File
        run: |
          cat > SendEmail.java << 'EOF'
          import java.util.Properties;
          import javax.mail.*;
          import javax.mail.internet.*;

          public class SendEmail {
              public static void main(String[] args) {
                  String host = System.getenv("SMTP_HOST");  
                  String port = System.getenv("SMTP_PORT");
                  String recipients = System.getenv("EMAIL_RECIPIENTS");
                  String sender = System.getenv("EMAIL_SENDER");
                  String username = System.getenv("SMTP_USERNAME");
                  String emailBody = System.getenv("EMAIL_BODY");

                  Properties props = new Properties();
                  props.put("mail.smtp.host", host);
                  props.put("mail.smtp.port", port);
                  props.put("mail.smtp.auth", "true");
                  props.put("mail.smtp.starttls.enable", "true");

                  Session session = Session.getInstance(props, new Authenticator() {
                      protected PasswordAuthentication getPasswordAuthentication() {
                          return new PasswordAuthentication(username, null);
                      }
                  });

                  try {
                      Message message = new MimeMessage(session);
                      message.setFrom(new InternetAddress(sender));
                      message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(recipients));
                      message.setSubject("Old Branches Report - " + java.time.LocalDate.now());
                      message.setText(emailBody);

                      Transport.send(message);
                      System.out.println("Email sent successfully!");

                  } catch (Exception e) {
                      e.printStackTrace();
                  }
              }
          }
          EOF

      - name: Compile Java Program with Maven
        run: |
          cd email-sender
          mvn compile

      - name: Run Java Email Sender with Maven
        run: |
          cd email-sender
          mvn exec:java -Dexec.mainClass="SendEmail"
          env:
            SMTP_HOST: "smtp.gmail.com"
            SMTP_PORT: "587"
            SMTP_USERNAME: "amrutpatange2@gmail.com"
            EMAIL_SENDER: "amrutpatange2@gmail.com"
            EMAIL_RECIPIENTS: "amrutpatange4598@gmail.com"
            EMAIL_BODY: "Demo Body"

        
      # - name: Compile Java Program
      #   run: javac -cp ".github/actions/external-jar/javax.mail-1.6.2.jar" -d . SendEmail.java

      # - name: Run Java Email Sender
      #   run: java -cp ".github/actions/external-jar/javax.mail-1.6.2.jar" SendEmail
      #   env:
      #     SMTP_HOST: "smtp.gmail.com"
      #     SMTP_PORT: "587"
      #     SMTP_USERNAME: "amrutpatange2@gmail.com"
      #     EMAIL_SENDER: "amrutpatange2@gmail.com"
      #     EMAIL_RECIPIENTS: "amrutpatange4598@gmail.com"
      #     EMAIL_BODY: "Demo Body"
